### ISSUE TITLE
How is this plugin supposed to work?

### ISSUE THREAD

**Issue by FunctionDJ** [yingpengsha/vite-plugin-tips#2]
When i add this to my config, nothing seems to change. There are also no new HTML nodes, and nothing happens when i kill Vite. I would have expected some sort of visual feedback, since that's what the plugin is for, right?

**Comment by yingpengsha** [comment]
Yes, in theory, when your vite server changes, a corresponding prompt will appear on your page.

Could you please provide us with your vite configuration and some of your environment configuration.  For example, whether you are using macos or windows, whether the package management tool you use is npm, yarn or pnpm, and what is the nodejs version.

Thank you in advance for providing this information, and I will try my best to help you solve the problem.

**Comment by FunctionDJ** [comment]
Here's my vite.config, sans config that's not relevant:
```ts
import { defineConfig } from "vite"
import compress from "vite-plugin-compression"
import react from "vite-preset-react"
import path from "path"

export default defineConfig(({ command }) => ({
  base: command === "serve" ? "" : "/build/",
  server: {
    fs: {
      allow: [path.resolve(__dirname, "..")]
    }
  },
  plugins: [
    react({
      removeDevtoolsInProd: true,
      injectReact: true
    }),
    // viteTips(), // TODO
    compress({ algorithm: "gzip" })
  ]
}))
```

My env:
Platform: Windows 10 20H2
Node v14.16.0
Package manager: npm v6.14.11
Vite v2.4.2

Thank you very much for taking a look into this!

**Comment by yingpengsha** [comment]
Frankly speaking, I strictly switched my environment to yours, and the configuration is the same, but there is no problem, and the tips will arrive on the page as expected.

So I hope you can provide a Reproduce Repo. This will help me to conduct a more specific investigation.

BTW, This is the [Reproduce Repo](https://github.com/yingpengsha/vite-tip-test-in-react-template) that I used for the test. The plugin worked fine in my environment. I hope it can give you some inspiration.

**Comment by FunctionDJ** [comment]
Thanks a lot, i'll try it and see if i can come up with a repo to reproduce the issue. I can't share my current project because it's company property. I'll come back when i get to it.

**Comment by yingpengsha** [comment]
If there is a new situation, I will restart the issue.
