### ISSUE TITLE
Missing type declaration

### ISSUE THREAD

**Issue by YangFong** [yingpengsha/vite-plugin-tips#4]
<img width="841" alt="image" src="https://github.com/yingpengsha/vite-plugin-tips/assets/70502828/0e09c721-bc60-4c43-96cc-3a066beef8ac">

**Comment by yingpengsha** [comment]
This is the latest version [vite-plugin-tips@2.1.1](https://www.npmjs.com/package/vite-plugin-tips), I hope it will solve your problem.

Thanks for the feedback ❤️

**Comment by YangFong** [comment]
@yingpengsha I've seen the update and the fix works, however it exposes another problem: the configuration option is not optional.

```ts
// Error, Type mismatch
ViteTips({
  update: false
})
```

An expectation adjustment:

```ts
// types.ts
export interface ViteTipsOptions {
  connect?: boolean
  update?: boolean
  disconnect?: boolean
}
```

**Comment by yingpengsha** [comment]
My bad, fixed. [vite-plugin-tips@2.1.2](https://www.npmjs.com/package/vite-plugin-tips)
